---
roles:
  master_of_masters:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 4096]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']
        - [modifyvm, !ruby/sym id, '--cpus', '4']
    provisioners:
      - type: shell
        inline: 'mkdir -p /etc/puppetlabs/puppet; cp /vagrant/trusted_facts/mom_csr_attributes.yaml /etc/puppetlabs/puppet/csr_attributes.yaml'
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts
      - type: pe_bootstrap
        role: !ruby/sym master
        answer_file: 'answer_files/aio.answer'
        autosign:
          - '*.vm'
          - '*.demo'
      - type: shell
        inline: "r10k deploy environment -pv"
#      - type: shell
#        inline: "/opt/puppetlabs/bin/puppet agent -t"
#      - type: shell
#        inline: "/vagrant/scripts/refresh_classes.sh"

  compile_master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: shell
        inline: 'mkdir -p /etc/puppetlabs/puppet; cp /vagrant/trusted_facts/compile_csr_attributes.yaml /etc/puppetlabs/puppet/csr_attributes.yaml'
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: shell
        inline: |-
                curl -sk https://master.puppetlabs.demo:8140/packages/current/install.bash | /bin/bash -s main:dns_alt_names=puppet

  windows_agent:
    guest: windows
    communicator: winrm
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - type: hosts
      - type: shell
        inline: 'Set-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA" -Value "0"'
      # The reload is important. It needs to happen for the name, domain, and
      # registry changes to take effect.
      - type: reload
      # Install the windows puppet agent using a PowerShell script. The
      # install_agent.ps1 script will set the agent certname it reads from
      # the system. The hosts provisioner should have configured these things
      # prior to the reboot.
      - type: shell
        path: "scripts/install_agent.ps1"
      - type: shell
        path: "scripts/install_forge_root_cert.ps1"
    synced_folders:
      - host_path:  '.files'
        guest_path: 'c:/seteam-files'

  posix_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: shell
        inline: |-
          curl -sk https://puppet.puppetlabs.demo:8140/packages/current/install.bash | /bin/bash

  gitlab_server:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--cpus', '2']
        - [modifyvm, !ruby/sym id, '--memory', 2048]
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
      - type: shell
        inline: |-
          curl -sk https://master.puppetlabs.demo:8140/packages/current/install.bash | /bin/bash

  darwin_agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}

  posix_noagent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
